import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
import "./globals.css";

// Components
import MainNav from "@/components/MainNav";
import PageTransition from "@/components/PageTransition";
import RectangleTransition from "@/components/RectangleTransition";


export const metadata = {
  title: "Home | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased overflow-hidden relative`}>
        <RectangleTransition />
        <PageTransition>
        <div className="flex">
          {/* main nav */}
          <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
          <div className="w-full max-w-[1130px] px-[15px] mx-auto">
            <header>header</header>
            <div>{children}</div>
          </div>
        </div>
        </PageTransition>
      </body>
    </html>
  );
}
